name: Deployment

on:
  push:
    branches:
      - lance-charts

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true

   steps:
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Deploy to production
    run: |
      echo "Deploying..."
      # Add your deployment script or commands here